---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tongtlcy/cmw.tongret.com/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R .cpanel.yml $DEPLOYPATH